# Generated by Django 4.2.7 on 2023-11-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('status', models.TextField(default='Default Status Text')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
