# Generated by Django 4.2.7 on 2023-11-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimen',
            name='status',
            field=models.TextField(default='input'),
        ),
    ]
