# Generated by Django 4.2.7 on 2023-11-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_sentimen_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='sentimen',
        ),
        migrations.DeleteModel(
            name='Sentimen',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
