# Generated by Django 4.2.7 on 2023-11-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_tweet_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=3)),
                ('birthday', models.DateField()),
                ('score', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'programmer',
            },
        ),
    ]
