# Generated by Django 4.2.7 on 2023-11-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_programmer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tweet',
            table='tweet',
        ),
    ]
