# Generated by Django 4.2.7 on 2023-11-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_tweet_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
