# Generated by Django 4.2.7 on 2023-11-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_delete_programmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='id',
            new_name='id_twt',
        ),
    ]
