# Generated by Django 4.2.7 on 2023-11-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_rename_id_tweet_id_twt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clean',
            fields=[
                ('id_twt', models.AutoField(primary_key=True, serialize=False)),
                ('full_text', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('tweet_url', models.URLField()),
                ('sentimen', models.ForeignKey(db_column='sentimen_id', on_delete=django.db.models.deletion.CASCADE, to='analysis.sentimen')),
            ],
            options={
                'db_table': 'clean',
            },
        ),
    ]
