# Generated by Django 4.2.7 on 2023-12-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean',
            name='sentimen',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='sentimen',
        ),
        migrations.DeleteModel(
            name='Sentimen',
        ),
    ]
