# Generated by Django 4.2.7 on 2023-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_tweet_idt'),
    ]

    operations = [
        migrations.AddField(
            model_name='clean',
            name='idt',
            field=models.IntegerField(default=0),
        ),
    ]
