# Generated by Django 4.2.7 on 2023-12-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_clean_idt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean',
            name='tweet_url',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='conversation_id_str',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='id_str',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='quote_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='reply_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_url',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user_id_str',
        ),
    ]
