# Generated by Django 4.2.7 on 2023-12-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_remove_clean_tweet_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id_twt', models.AutoField(primary_key=True, serialize=False)),
                ('full_text', models.TextField()),
            ],
            options={
                'db_table': 'trans',
            },
        ),
    ]
