# Generated by Django 4.2.7 on 2023-12-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_trans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id_twt', models.AutoField(primary_key=True, serialize=False)),
                ('full_text', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('idt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'testing',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id_twt', models.AutoField(primary_key=True, serialize=False)),
                ('full_text', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('idt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'training',
            },
        ),
        migrations.DeleteModel(
            name='Trans',
        ),
    ]
