# Generated by Django 4.2.7 on 2023-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_testing_training_delete_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='depresi',
            field=models.TextField(default='yes'),
        ),
        migrations.AddField(
            model_name='training',
            name='compound_Score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='depresi',
            field=models.TextField(default='yes'),
        ),
        migrations.AddField(
            model_name='training',
            name='sentiment',
            field=models.TextField(default='netral'),
        ),
    ]
