# Generated by Django 4.2.7 on 2023-12-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_testing_depresi_training_compound_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='compound_Score',
            new_name='compound_score',
        ),
    ]
