# Generated by Django 4.2.7 on 2023-12-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_rename_compound_score_training_compound_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='predict',
            field=models.TextField(default='Yes'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='depresi',
            field=models.TextField(default='Yes'),
        ),
        migrations.AlterField(
            model_name='training',
            name='depresi',
            field=models.TextField(default='Yes'),
        ),
        migrations.AlterField(
            model_name='training',
            name='sentiment',
            field=models.TextField(default='Netral'),
        ),
    ]
