# Generated by Django 4.2.7 on 2023-12-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_training_predict_alter_testing_depresi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='predict',
        ),
    ]
