# Generated by Django 4.2.7 on 2023-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_remove_training_predict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='depresi',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='training',
            name='depresi',
            field=models.TextField(default=''),
        ),
    ]
