# Generated by Django 4.2.7 on 2023-12-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_alter_testing_depresi_alter_training_depresi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='idt',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='username',
        ),
    ]
